'use client'
import { useEffect, useRef } from "react";
import PaneFlow from "./paneflow";
import "./paneflow.css";
import "./MyPaneFlow.css";

export default function MyPaneFlow() {
  const paneFlowElRef = useRef(null);
  const paneFlowInstanceRef = useRef(null);

  useEffect(() => {
    if (paneFlowElRef.current) {
      paneFlowInstanceRef.current = new PaneFlow({
        el: paneFlowElRef.current,
        padding: "2cqw",
        gap: "2cqw",
        transitionDuration: 1000,
        blockDelay: 50,
        blockBorderRadius: "0cqw",
        initialPaneIndex: 0,
        autoplay: { enabled: true, interval: 4000 },
        pagination: { enabled: true, clickable: true, type: "bullets" },
        panes: [
          {
            cols: 3,
            rows: 2,
            blocks: [
              {
                el: ".paneflow-block-cecCQP",
                col: 0,
                row: 0,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-3Mk7IA",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-mFFbWz",
                    translateX: "-0.8cqw",
                    translateY: "-21cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 10,
                  },
                  {
                    el: ".paneflow-item-VxgdSP",
                    translateX: "0.2cqw",
                    translateY: "-6.7cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 10,
                  },
                ],
                enterFrom: "top-left",
                exitTo: "top-left",
              },
              {
                el: ".paneflow-block-zhpyj4",
                col: 1,
                row: 0,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-2UkykL",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-q85vfo",
                    translateX: "-9.1cqw",
                    translateY: "-19cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                    parallax: 10,
                  },
                  {
                    el: ".paneflow-item-Sh2rd4",
                    translateX: "-8cqw",
                    translateY: "-21.7cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 10,
                  },
                ],
                enterFrom: "top",
                exitTo: "top",
              },
              {
                el: ".paneflow-block-Fcxpiu",
                col: 2,
                row: 0,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-HSKOhH",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-xLKo6r",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                    parallax: 10,
                  },
                  {
                    el: ".paneflow-item-bbwN20",
                    translateX: "-14.6cqw",
                    translateY: "-19.8cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 10,
                  },
                ],
                enterFrom: "top-right",
                exitTo: "top-right",
              },
              {
                el: ".paneflow-block-xvmHDf",
                col: 0,
                row: 1,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-A36PhO",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-uFoVzK",
                    translateX: "-25.8cqw",
                    translateY: "-38.3cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 10,
                  },
                  {
                    el: ".paneflow-item-D9WF08",
                    translateX: "-10.1cqw",
                    translateY: "-47.1cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 10,
                  },
                ],
                enterFrom: "bottom-left",
                exitTo: "bottom-left",
              },
              {
                el: ".paneflow-block-Ak5Jts",
                col: 1,
                row: 1,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-nyG95x",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-mfo1tD",
                    translateX: "0cqw",
                    translateY: "0cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                ],
                enterFrom: "bottom",
                exitTo: "bottom",
              },
              {
                el: ".paneflow-block-v12cRX",
                col: 2,
                row: 1,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-eVgPrm",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-fr5OwG",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                ],
                enterFrom: "bottom-right",
                exitTo: "bottom-right",
              },
            ],
            autoplayInternal: 0,
          },
          {
            cols: 1,
            rows: 1,
            blocks: [
              {
                el: ".paneflow-block-cecCQP",
                col: 0,
                row: 0,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-3Mk7IA",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                  {
                    el: ".paneflow-item-mFFbWz",
                    translateX: "-50.6cqw",
                    translateY: "14.1cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 0.27,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                  {
                    el: ".paneflow-item-VxgdSP",
                    translateX: "16.5cqw",
                    translateY: "12.1cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 0.84,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "right",
                exitTo: "left",
              },
            ],
          },
          {
            cols: 4,
            rows: 3,
            blocks: [
              {
                el: ".paneflow-block-cecCQP",
                col: 0,
                row: 0,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-3Mk7IA",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-mFFbWz",
                    translateX: "-9.6cqw",
                    translateY: "-25.9cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                  {
                    el: ".paneflow-item-VxgdSP",
                    translateX: "2.2cqw",
                    translateY: "-20.9cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "top-left",
                exitTo: "top-left",
              },
              {
                el: ".paneflow-block-zhpyj4",
                col: 1,
                row: 0,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-2UkykL",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-q85vfo",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                  {
                    el: ".paneflow-item-Sh2rd4",
                    translateX: "-10cqw",
                    translateY: "-20.1cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "top",
                exitTo: "top",
              },
              {
                el: ".paneflow-block-Fcxpiu",
                col: 2,
                row: 0,
                widthCols: 2,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-HSKOhH",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-xLKo6r",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                  {
                    el: ".paneflow-item-bbwN20",
                    translateX: "-4.8cqw",
                    translateY: "-16.6cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "top-right",
                exitTo: "top-right",
              },
              {
                el: ".paneflow-block-xvmHDf",
                col: 0,
                row: 1,
                widthCols: 1,
                heightRows: 2,
                children: [
                  {
                    el: ".paneflow-item-A36PhO",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-uFoVzK",
                    translateX: "-12.2cqw",
                    translateY: "-35.6cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                  {
                    el: ".paneflow-item-D9WF08",
                    translateX: "-6cqw",
                    translateY: "42.5cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "bottom-left",
                exitTo: "bottom-left",
              },
              {
                el: ".paneflow-block-Ak5Jts",
                col: 1,
                row: 1,
                widthCols: 1,
                heightRows: 2,
                children: [
                  {
                    el: ".paneflow-item-nyG95x",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-mfo1tD",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                ],
                enterFrom: "bottom",
                exitTo: "bottom",
              },
              {
                el: ".paneflow-block-v12cRX",
                col: 2,
                row: 1,
                widthCols: 2,
                heightRows: 2,
                children: [
                  {
                    el: ".paneflow-item-eVgPrm",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-fr5OwG",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                ],
                enterFrom: "bottom-right",
                exitTo: "bottom-right",
              },
            ],
            autoplayInternal: 0,
          },
          {
            cols: 1,
            rows: 1,
            blocks: [
              {
                el: ".paneflow-block-zhpyj4",
                col: 0,
                row: 0,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-2UkykL",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-q85vfo",
                    translateX: "-51cqw",
                    translateY: "6.6cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 0.34,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 10,
                  },
                  {
                    el: ".paneflow-item-Sh2rd4",
                    translateX: "-46.4cqw",
                    translateY: "11.5cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 0.32,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "right",
                exitTo: "left",
              },
            ],
          },
          {
            cols: 3,
            rows: 3,
            blocks: [
              {
                el: ".paneflow-block-cecCQP",
                col: 0,
                row: 0,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-3Mk7IA",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-mFFbWz",
                    translateX: "-7.9cqw",
                    translateY: "-16.3cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                  {
                    el: ".paneflow-item-VxgdSP",
                    translateX: "0.3cqw",
                    translateY: "-22.6cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "top-left",
                exitTo: "top-left",
              },
              {
                el: ".paneflow-block-zhpyj4",
                col: 1,
                row: 0,
                widthCols: 1,
                heightRows: 2,
                children: [
                  {
                    el: ".paneflow-item-2UkykL",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-q85vfo",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                  {
                    el: ".paneflow-item-Sh2rd4",
                    translateX: "-3.9cqw",
                    translateY: "-17.8cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "top",
                exitTo: "top",
              },
              {
                el: ".paneflow-block-Fcxpiu",
                col: 2,
                row: 0,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-HSKOhH",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-xLKo6r",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                  {
                    el: ".paneflow-item-bbwN20",
                    translateX: "-5.5cqw",
                    translateY: "-16.8cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "top-right",
                exitTo: "top-right",
              },
              {
                el: ".paneflow-block-xvmHDf",
                col: 0,
                row: 1,
                widthCols: 1,
                heightRows: 2,
                children: [
                  {
                    el: ".paneflow-item-A36PhO",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-uFoVzK",
                    translateX: "-17.6cqw",
                    translateY: "-36.8cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                  {
                    el: ".paneflow-item-D9WF08",
                    translateX: "-4.3cqw",
                    translateY: "-39.6cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "bottom-left",
                exitTo: "bottom-left",
              },
              {
                el: ".paneflow-block-v12cRX",
                col: 2,
                row: 1,
                widthCols: 1,
                heightRows: 2,
                children: [
                  {
                    el: ".paneflow-item-eVgPrm",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-fr5OwG",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                ],
                enterFrom: "bottom-right",
                exitTo: "bottom-right",
              },
              {
                el: ".paneflow-block-Ak5Jts",
                col: 1,
                row: 2,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-nyG95x",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-mfo1tD",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                ],
                enterFrom: "bottom",
                exitTo: "bottom",
              },
            ],
            autoplayInternal: 0,
          },
          {
            cols: 1,
            rows: 1,
            blocks: [
              {
                el: ".paneflow-block-Fcxpiu",
                col: 0,
                row: 0,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-HSKOhH",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-xLKo6r",
                    translateX: "-59.3cqw",
                    translateY: "10.5cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 0.28,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 10,
                  },
                  {
                    el: ".paneflow-item-bbwN20",
                    translateX: "-40.7cqw",
                    translateY: "14.9cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 0.3,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "right",
                exitTo: "left",
              },
            ],
          },
          {
            cols: 6,
            rows: 2,
            blocks: [
              {
                el: ".paneflow-block-cecCQP",
                col: 0,
                row: 0,
                widthCols: 1,
                heightRows: 2,
                children: [
                  {
                    el: ".paneflow-item-3Mk7IA",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-mFFbWz",
                    translateX: "-5.6cqw",
                    translateY: "-24.2cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                  {
                    el: ".paneflow-item-VxgdSP",
                    translateX: "1.8cqw",
                    translateY: "-17.5cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "top",
                exitTo: "top",
              },
              {
                el: ".paneflow-block-xvmHDf",
                col: 1,
                row: 0,
                widthCols: 1,
                heightRows: 2,
                children: [
                  {
                    el: ".paneflow-item-A36PhO",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-uFoVzK",
                    translateX: "-6.6cqw",
                    translateY: "-18.6cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                  {
                    el: ".paneflow-item-D9WF08",
                    translateX: "-0.7cqw",
                    translateY: "-24.7cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "bottom",
                exitTo: "bottom",
              },
              {
                el: ".paneflow-block-zhpyj4",
                col: 2,
                row: 0,
                widthCols: 1,
                heightRows: 2,
                children: [
                  {
                    el: ".paneflow-item-2UkykL",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-q85vfo",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                  {
                    el: ".paneflow-item-Sh2rd4",
                    translateX: "-2.7cqw",
                    translateY: "-18.3cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "top",
                exitTo: "top",
              },
              {
                el: ".paneflow-block-Ak5Jts",
                col: 3,
                row: 0,
                widthCols: 1,
                heightRows: 2,
                children: [
                  {
                    el: ".paneflow-item-nyG95x",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-mfo1tD",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                ],
                enterFrom: "bottom",
                exitTo: "bottom",
              },
              {
                el: ".paneflow-block-Fcxpiu",
                col: 4,
                row: 0,
                widthCols: 1,
                heightRows: 2,
                children: [
                  {
                    el: ".paneflow-item-HSKOhH",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-xLKo6r",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                  {
                    el: ".paneflow-item-bbwN20",
                    translateX: "-5.6cqw",
                    translateY: "-18.9cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "top",
                exitTo: "top",
              },
              {
                el: ".paneflow-block-v12cRX",
                col: 5,
                row: 0,
                widthCols: 1,
                heightRows: 2,
                children: [
                  {
                    el: ".paneflow-item-eVgPrm",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-fr5OwG",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                ],
                enterFrom: "bottom",
                exitTo: "bottom",
              },
            ],
            autoplayInternal: 0,
          },
          {
            cols: 1,
            rows: 1,
            blocks: [
              {
                el: ".paneflow-block-xvmHDf",
                col: 0,
                row: 0,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-A36PhO",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-uFoVzK",
                    translateX: "-7cqw",
                    translateY: "13.9cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 0.58,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                  {
                    el: ".paneflow-item-D9WF08",
                    translateX: "-45.2cqw",
                    translateY: "16.2cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 0.3,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "right",
                exitTo: "left",
              },
            ],
          },
          {
            cols: 6,
            rows: 3,
            blocks: [
              {
                el: ".paneflow-block-cecCQP",
                col: 0,
                row: 0,
                widthCols: 3,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-3Mk7IA",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-mFFbWz",
                    translateX: "-8.1cqw",
                    translateY: "-24.2cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                  {
                    el: ".paneflow-item-VxgdSP",
                    translateX: "1.7cqw",
                    translateY: "-16.4cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "left",
                exitTo: "left",
              },
              {
                el: ".paneflow-block-Fcxpiu",
                col: 3,
                row: 0,
                widthCols: 3,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-HSKOhH",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-xLKo6r",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                  {
                    el: ".paneflow-item-bbwN20",
                    translateX: "-2.5cqw",
                    translateY: "-33cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "right",
                exitTo: "right",
              },
              {
                el: ".paneflow-block-zhpyj4",
                col: 0,
                row: 1,
                widthCols: 3,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-2UkykL",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-q85vfo",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                  {
                    el: ".paneflow-item-Sh2rd4",
                    translateX: "-19.5cqw",
                    translateY: "-43.7cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "left",
                exitTo: "left",
              },
              {
                el: ".paneflow-block-Ak5Jts",
                col: 3,
                row: 1,
                widthCols: 3,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-nyG95x",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-mfo1tD",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                ],
                enterFrom: "right",
                exitTo: "right",
              },
              {
                el: ".paneflow-block-xvmHDf",
                col: 0,
                row: 2,
                widthCols: 3,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-A36PhO",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-uFoVzK",
                    translateX: "0.7cqw",
                    translateY: "26.6cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                  {
                    el: ".paneflow-item-D9WF08",
                    translateX: "9.2cqw",
                    translateY: "37.2cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "left",
                exitTo: "left",
              },
              {
                el: ".paneflow-block-v12cRX",
                col: 3,
                row: 2,
                widthCols: 3,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-eVgPrm",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-fr5OwG",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                ],
                enterFrom: "right",
                exitTo: "right",
              },
            ],
            autoplayInternal: 0,
          },
          {
            cols: 6,
            rows: 3,
            blocks: [
              {
                el: ".paneflow-block-cecCQP",
                col: 0,
                row: 0,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-3Mk7IA",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-mFFbWz",
                    translateX: "1cqw",
                    translateY: "-18.3cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                  {
                    el: ".paneflow-item-VxgdSP",
                    translateX: "1.9cqw",
                    translateY: "-17.4cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "left",
                exitTo: "left",
              },
              {
                el: ".paneflow-block-zhpyj4",
                col: 1,
                row: 0,
                widthCols: 2,
                heightRows: 2,
                children: [
                  {
                    el: ".paneflow-item-2UkykL",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-q85vfo",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                  {
                    el: ".paneflow-item-Sh2rd4",
                    translateX: "0.9cqw",
                    translateY: "-20.9cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "top",
                exitTo: "top",
              },
              {
                el: ".paneflow-block-Fcxpiu",
                col: 3,
                row: 0,
                widthCols: 3,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-HSKOhH",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-xLKo6r",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                  {
                    el: ".paneflow-item-bbwN20",
                    translateX: "-13.5cqw",
                    translateY: "-30.7cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "top",
                exitTo: "top",
              },
              {
                el: ".paneflow-block-bFL41T",
                col: 0,
                row: 1,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-ihLog9",
                    translateX: "2.5cqw",
                    translateY: "4.4cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 2.3,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "right",
                exitTo: "left",
              },
              {
                el: ".paneflow-block-Ak5Jts",
                col: 3,
                row: 1,
                widthCols: 2,
                heightRows: 2,
                children: [
                  {
                    el: ".paneflow-item-nyG95x",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-mfo1tD",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                ],
                enterFrom: "bottom",
                exitTo: "bottom",
              },
              {
                el: ".paneflow-block-v12cRX",
                col: 5,
                row: 1,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-eVgPrm",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-fr5OwG",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 0,
                  },
                ],
                enterFrom: "right",
                exitTo: "right",
              },
              {
                el: ".paneflow-block-xvmHDf",
                col: 0,
                row: 2,
                widthCols: 2,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-A36PhO",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                  },
                  {
                    el: ".paneflow-item-uFoVzK",
                    translateX: "0.6cqw",
                    translateY: "25.9cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                  {
                    el: ".paneflow-item-D9WF08",
                    translateX: "-2.7cqw",
                    translateY: "35.9cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 1,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "bottom",
                exitTo: "bottom",
              },
              {
                el: ".paneflow-block-Padeqh",
                col: 2,
                row: 2,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-jWlS9a",
                    translateX: 0,
                    translateY: 0,
                    translateZ: 0,
                    rotate: 0,
                    scale: 2.31,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "right",
                exitTo: "left",
              },
              {
                el: ".paneflow-block-JTUYKF",
                col: 5,
                row: 2,
                widthCols: 1,
                heightRows: 1,
                children: [
                  {
                    el: ".paneflow-item-7jwADI",
                    translateX: "5.5cqw",
                    translateY: "5cqw",
                    translateZ: 0,
                    rotate: 0,
                    scale: 2.14,
                    transformOrigin: "center",
                    opacity: 1,
                    parallax: 0,
                  },
                ],
                enterFrom: "right",
                exitTo: "left",
              },
            ],
            autoplayInternal: 0,
          },
        ],
        intro: true,
        navigation: { enabled: true },
      });
    }
    return () => {
      if (paneFlowInstanceRef.current) {
        paneFlowInstanceRef.current.destroy();
      }
    };
  }, []);
  return (
    <div
      ref={paneFlowElRef}
      className="paneflow paneflow-unchanged-vonni-421 paneflow-with-pagination"
    >
      <div className="paneflow-content">
        <div className="paneflow-block paneflow-block-cecCQP">
          <div className="paneflow-bg-image paneflow-item-3Mk7IA">
            <img src="https://cdn.paneflow.com/unchanged-vonni-421/80da7e9387f660b2dabb.png" />
          </div>
          <div className="paneflow-text paneflow-item-mFFbWz">
            <div className="paneflow-text-container">
              <div className="paneflow-text-content">
                Nascemos em Belém do Pará e levamos o melhor da região Norte
                para todo o Brasil.
                <br />
                &nbsp;Origem que se sente no sabor.
              </div>
            </div>
          </div>
          <div className="paneflow-text paneflow-item-VxgdSP">
            <div className="paneflow-text-container">
              <div className="paneflow-text-content">
                Da Amazônia para sua mesa
              </div>
            </div>
          </div>
        </div>
        <div className="paneflow-block paneflow-block-zhpyj4">
          <div className="paneflow-bg-image paneflow-item-2UkykL">
            <img src="https://cdn.paneflow.com/unchanged-vonni-421/7ff868a17af8bbd3f354.png" />
          </div>
          <div className="paneflow-text paneflow-item-q85vfo">
            <div className="paneflow-text-container">
              <div className="paneflow-text-content">
                Qualidade que alimenta confiança
              </div>
            </div>
          </div>
          <div className="paneflow-text paneflow-item-Sh2rd4">
            <div className="paneflow-text-container">
              <div className="paneflow-text-content">
                Selecionamos, cuidamos e entregamos com responsabilidade.
                <br />
                Nosso compromisso é com a excelência em cada produto.
              </div>
            </div>
          </div>
        </div>
        <div className="paneflow-block paneflow-block-Fcxpiu">
          <div className="paneflow-bg-image paneflow-item-HSKOhH">
            <img src="https://cdn.paneflow.com/unchanged-vonni-421/7870bc11792a02a3e31a.png" />
          </div>
          <div className="paneflow-text paneflow-item-xLKo6r">
            <div className="paneflow-text-container">
              <div className="paneflow-text-content">
                Variedade que atende todos os públicos
              </div>
            </div>
          </div>
          <div className="paneflow-text paneflow-item-bbwN20">
            <div className="paneflow-text-container">
              <div className="paneflow-text-content">
                Do consumidor final às grandes empresas, pescados, carnes,
                <br />
                frutas e muito mais com a qualidade JC Select.
              </div>
            </div>
          </div>
        </div>
        <div className="paneflow-block paneflow-block-xvmHDf">
          <div className="paneflow-bg-image paneflow-item-A36PhO">
            <img src="https://cdn.paneflow.com/unchanged-vonni-421/c004f4ed4d0f487586b4.png" />
          </div>
          <div className="paneflow-text paneflow-item-uFoVzK">
            <div className="paneflow-text-container">
              <div className="paneflow-text-content">
                Alimentos com identidade brasileira
              </div>
            </div>
          </div>
          <div className="paneflow-text paneflow-item-D9WF08">
            <div className="paneflow-text-container">
              <div className="paneflow-text-content">
                Mais que alimentos: entregamos cultura, frescor e respeito às
                raízes.
                <br />
                &nbsp;Uma marca conectada com o território.
              </div>
            </div>
          </div>
        </div>
        <div className="paneflow-block paneflow-block-Ak5Jts">
          <div className="paneflow-bg-image paneflow-item-nyG95x">
            <img src="https://cdn.paneflow.com/unchanged-vonni-421/efab59c50ea9d0b3ec20.png" />
          </div>
          <div className="paneflow-text paneflow-item-mfo1tD">
            <div className="paneflow-text-container">
              <div className="paneflow-text-content">Style in Motion</div>
            </div>
          </div>
        </div>
        <div className="paneflow-block paneflow-block-v12cRX">
          <div className="paneflow-bg-image paneflow-item-eVgPrm">
            <img src="https://cdn.paneflow.com/unchanged-vonni-421/d3bbe7ce6a60daadccb5.png" />
          </div>
          <div className="paneflow-text paneflow-item-fr5OwG">
            <div className="paneflow-text-container">
              <div className="paneflow-text-content">Red Means Power</div>
            </div>
          </div>
        </div>
        <div className="paneflow-block paneflow-block-bFL41T">
          <div className="paneflow-image paneflow-item-ihLog9">
            <img src="https://cdn.paneflow.com/unchanged-vonni-421/16636a18946e20516daf.png" />
          </div>
        </div>
        <div className="paneflow-block paneflow-block-Padeqh">
          <div className="paneflow-image paneflow-item-jWlS9a">
            <img src="https://cdn.paneflow.com/unchanged-vonni-421/6d555502b4521e6815e4.png" />
          </div>
        </div>
        <div className="paneflow-block paneflow-block-JTUYKF">
          <div className="paneflow-image paneflow-item-7jwADI">
            <img src="https://cdn.paneflow.com/unchanged-vonni-421/8d600dce5927ac50950f.png" />
          </div>
        </div>
      </div>
    </div>
  );
}
